language: java
sudo: false
dist: trusty
install: mvn clean package --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn verify --fail-at-end -U -V
notifications:
  email:
    on_failure: change
matrix:
  include:
    # Quality testing
    - jdk: oraclejdk8
      env: JACOCO=true RELEASE_CHECKS=true
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - jdk: oraclejdk8
      env: JACOCO=true SONAR=publish
      script: mvn clean verify sonar:sonar --fail-at-end -U -V
    # Performance testing
    - jdk: openjdk8
      env: JACOCO=false
    - jdk: oraclejdk9
      env: JACOCO=false
    - jdk: oraclejdk11
      env: JACOCO=false
